/**
 * Deterministic HTML report for version compare. No AI.
 */

import type { VersionCompareResult } from "@/core/services/compare/versionCompare";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatValue(v: unknown): string {
  if (v == null) return "—";
  if (typeof v === "string" || typeof v === "number") return String(v);
  return JSON.stringify(v);
}

export function buildCompareReportHtml(
  result: VersionCompareResult,
  options: { contractTitle: string; policyName: string; workspaceName?: string }
): string {
  const { contractTitle, policyName, workspaceName = "" } = options;
  const { from, to, delta, changes, topDrivers } = result;
  const changedItems = changes.filter((c) => c.changeType !== "UNCHANGED");
  const date = new Date().toISOString().slice(0, 10);

  const sections: string[] = [];
  sections.push(`<h1>Version Compare Report</h1>`);
  sections.push(`<p><strong>Contract:</strong> ${esc(contractTitle)}</p>`);
  sections.push(`<p><strong>Policy:</strong> ${esc(policyName)}</p>`);
  if (workspaceName) sections.push(`<p><strong>Workspace:</strong> ${esc(workspaceName)}</p>`);
  sections.push(`<p><strong>Date:</strong> ${esc(date)}</p>`);

  sections.push(`<h2>Score Summary</h2>`);
  sections.push(`<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse">`);
  sections.push(`<tr><th>Version</th><th>Raw Score</th><th>Effective Score</th></tr>`);
  sections.push(`<tr><td>v${from.versionNumber}</td><td>${from.rawScore}</td><td>${from.effectiveScore}</td></tr>`);
  sections.push(`<tr><td>v${to.versionNumber}</td><td>${to.rawScore}</td><td>${to.effectiveScore}</td></tr>`);
  sections.push(`</table>`);
  sections.push(`<p><strong>Delta:</strong> ${delta.raw} (raw), ${delta.effective} (effective) — <strong>${esc(delta.label)}</strong></p>`);

  if (topDrivers.length > 0) {
    sections.push(`<h2>Top Drivers</h2>`);
    sections.push(`<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse">`);
    sections.push(`<tr><th>Clause Type</th><th>Key</th><th>Delta Impact</th><th>Reason</th></tr>`);
    for (const d of topDrivers) {
      sections.push(`<tr><td>${esc(d.clauseType)}</td><td>${esc(d.key)}</td><td>${d.deltaImpact}</td><td>${esc(d.reason)}</td></tr>`);
    }
    sections.push(`</table>`);
  }

  if (changedItems.length > 0) {
    sections.push(`<h2>Changes (${changedItems.length})</h2>`);
    sections.push(`<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse; width:100%">`);
    sections.push(`<tr><th>Clause</th><th>Type</th><th>From (v${from.versionNumber})</th><th>To (v${to.versionNumber})</th><th>Why</th></tr>`);
    for (const c of changedItems) {
      const fromStatus = c.from ? `${c.from.status}${c.from.overridden ? " (overridden)" : ""}` : "—";
      const toStatus = c.to ? `${c.to.status}${c.to.overridden ? " (overridden)" : ""}` : "—";
      const fromVal = c.from?.foundValue != null ? formatValue(c.from.foundValue) : "—";
      const toVal = c.to?.foundValue != null ? formatValue(c.to.foundValue) : "—";
      sections.push(
        `<tr><td>${esc(c.clauseType)}</td><td>${esc(c.changeType)}</td><td>${esc(fromStatus)} / ${esc(fromVal.slice(0, 80))}</td><td>${esc(toStatus)} / ${esc(toVal.slice(0, 80))}</td><td>${esc(c.why ?? "—")}</td></tr>`
      );
    }
    sections.push(`</table>`);
  } else {
    sections.push(`<p>No changes between versions for this policy.</p>`);
  }

  sections.push(`<p style="margin-top:2em; font-size:0.9em; color:#666">Generated by Contract Intelligence OS${workspaceName ? ` · ${esc(workspaceName)}` : ""}</p>`);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Version Compare: ${esc(contractTitle)}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2em auto; padding: 0 1em; }
    table { width: 100%; margin: 1em 0; }
    th { text-align: left; background: #f0f0f0; }
  </style>
</head>
<body>
${sections.join("\n")}
</body>
</html>`;
}
