-- Step 7: Add VERSION_COMPARED and REPORT_EXPORTED to LedgerEventType
ALTER TYPE "LedgerEventType" ADD VALUE IF NOT EXISTS 'VERSION_COMPARED';
ALTER TYPE "LedgerEventType" ADD VALUE IF NOT EXISTS 'REPORT_EXPORTED';
