/**
 * STEP 9A: Deterministic HTML report for executive summary. No AI.
 */

import type { RiskAggregation } from "./riskAggregation";
import type { ExecutiveSummary } from "./executiveSummary";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildExecutiveSummaryHtml(
  aggregation: RiskAggregation,
  summary: ExecutiveSummary,
  options: { contractTitle: string; policyName: string; workspaceName?: string }
): string {
  const { contractTitle, policyName, workspaceName = "" } = options;
  const { effectiveScore, rawScore, clusters } = aggregation;
  const date = new Date(aggregation.generatedAt).toISOString().slice(0, 10);

  const sections: string[] = [];
  sections.push(`<h1>Executive Risk Summary</h1>`);
  sections.push(`<p><strong>Contract:</strong> ${esc(contractTitle)}</p>`);
  sections.push(`<p><strong>Policy:</strong> ${esc(policyName)}</p>`);
  if (workspaceName) sections.push(`<p><strong>Workspace:</strong> ${esc(workspaceName)}</p>`);
  sections.push(`<p><strong>Date:</strong> ${esc(date)}</p>`);

  sections.push(`<h2>${esc(summary.headline)}</h2>`);
  sections.push(
    `<p>Score: <strong>${effectiveScore}/100</strong>${effectiveScore !== rawScore ? ` (raw ${rawScore})` : ""}</p>`
  );
  for (const p of summary.paragraphs) {
    sections.push(`<p>${esc(p)}</p>`);
  }

  sections.push(`<h2>Risk clusters</h2>`);
  sections.push(`<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse">`);
  sections.push(
    `<tr><th>Risk type</th><th>Level</th><th>Violations</th><th>Unclear</th><th>Overridden</th><th>Max severity</th></tr>`
  );
  for (const c of clusters) {
    sections.push(
      `<tr><td>${esc(c.riskType)}</td><td>${esc(c.level)}</td><td>${c.violationCount}</td><td>${c.unclearCount}</td><td>${c.overriddenCount}</td><td>${c.maxSeverity ?? "—"}</td></tr>`
    );
  }
  sections.push(`</table>`);

  if (summary.keyRisks.length > 0) {
    sections.push(`<h2>Key risks</h2><ul>`);
    for (const k of summary.keyRisks) {
      sections.push(`<li>${esc(k)}</li>`);
    }
    sections.push(`</ul>`);
  }

  sections.push(`<h2>Recommendation</h2>`);
  sections.push(`<p><strong>${esc(summary.recommendation)}</strong></p>`);

  sections.push(
    `<p style="margin-top:2em; font-size:0.9em; color:#666">Generated by Contract Intelligence OS${workspaceName ? ` · ${esc(workspaceName)}` : ""}</p>`
  );

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Executive Summary: ${esc(contractTitle)}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2em auto; padding: 0 1em; }
    table { width: 100%; margin: 1em 0; }
    th { text-align: left; background: #f0f0f0; }
  </style>
</head>
<body>
${sections.join("\n")}
</body>
</html>`;
}
